/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Hobby = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
});

export const idlService = IDL.Service({
  'addHobby' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'getHobbies' : IDL.Func([], [IDL.Vec(Hobby)], ['query']),
  'removeHobby' : IDL.Func([IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Hobby = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
  });
  
  return IDL.Service({
    'addHobby' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'getHobbies' : IDL.Func([], [IDL.Vec(Hobby)], ['query']),
    'removeHobby' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };